#!/usr/bin/env bash
set -euo pipefail
BASE="$(pwd)/arunroo_project"
mkdir -p "$BASE/brand/logo_panonniwet"
mkdir -p "$BASE/content/quotes/2025-08"
mkdir -p "$BASE/content/greetings"
mkdir -p "$BASE/content/captions"
mkdir -p "$BASE/prompts/image"
mkdir -p "$BASE/prompts/video"
mkdir -p "$BASE/assets/images_src"
mkdir -p "$BASE/assets/images_final/square"
mkdir -p "$BASE/assets/images_final/portrait"
mkdir -p "$BASE/assets/images_final/story"
mkdir -p "$BASE/assets/videos_final"
mkdir -p "$BASE/schedules"
mkdir -p "$BASE/automation/n8n"
mkdir -p "$BASE/automation/scripts"
mkdir -p "$BASE/logs"
mkdir -p "$BASE/docs"
mkdir -p "$BASE/outputs/reports"
echo "สร้างโครงสร้างโฟลเดอร์ ArunRoo เสร็จแล้ว: $BASE"
